// Student Sphere Demo Data

// Demo Services Data
const demoServices = [
  {
    id: "1",
    title: "Python Programming Tutoring",
    description: "Expert help with Python, data structures, and algorithms. Perfect for first and second years. I've tutored 20+ students with a 90% pass rate.",
    price: 150,
    category: "tutoring",
    location: "University of Cape Town",
    sellerName: "Thabo Khumalo",
    sellerAvatar: "https://ui-avatars.com/api/?name=Thabo+Khumalo&background=667eea&color=fff",
    sellerPhone: "27821234567",
    sellerUniversity: "University of Cape Town",
    sellerRating: 4.8,
    sellerMemberSince: "January 2024",
    verified: true,
    paymentMethods: ["Cash", "EFT"],
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop",
  },
  {
    id: "2",
    title: "Laptop & Phone Repair",
    description: "Professional repair services for laptops, phones, and tablets. Screen replacements, software issues, and hardware upgrades. Same-day service available.",
    price: 200,
    category: "tech",
    location: "University of Witwatersrand",
    sellerName: "Lerato Naidoo",
    sellerAvatar: "https://ui-avatars.com/api/?name=Lerato+Naidoo&background=764ba2&color=fff",
    sellerPhone: "27829876543",
    sellerUniversity: "University of Witwatersrand",
    sellerRating: 4.9,
    sellerMemberSince: "February 2024",
    verified: true,
    paymentMethods: ["Cash", "EFT", "Card"],
    imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600&h=400&fit=crop",
  },
  {
    id: "3",
    title: "Professional Makeup & Hair",
    description: "Makeup and hair styling for events, photoshoots, and special occasions. Experienced with all skin tones and hair types. Portfolio available.",
    price: 250,
    category: "beauty",
    location: "Stellenbosch University",
    sellerName: "Zanele Moyo",
    sellerAvatar: "https://ui-avatars.com/api/?name=Zanele+Moyo&background=d63384&color=fff",
    sellerPhone: "27835551234",
    sellerUniversity: "Stellenbosch University",
    sellerRating: 5.0,
    sellerMemberSince: "March 2024",
    verified: true,
    paymentMethods: ["Cash", "EFT"],
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop",
  },
  {
    id: "4",
    title: "Homemade Meal Prep Services",
    description: "Healthy, delicious meal prep for busy students. Weekly packages available. Dietary restrictions accommodated. Free delivery on campus.",
    price: 120,
    category: "food",
    location: "University of Pretoria",
    sellerName: "Sipho Dlamini",
    sellerAvatar: "https://ui-avatars.com/api/?name=Sipho+Dlamini&background=fd7e14&color=fff",
    sellerPhone: "27841112222",
    sellerUniversity: "University of Pretoria",
    sellerRating: 4.7,
    sellerMemberSince: "December 2023",
    verified: true,
    paymentMethods: ["Cash", "EFT"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: "5",
    title: "Mathematics Tutoring (All Levels)",
    description: "Struggling with maths? I can help! From first year calculus to third year statistics. Flexible scheduling and affordable rates.",
    price: 130,
    category: "tutoring",
    location: "Rhodes University",
    sellerName: "Nomsa Khumalo",
    sellerAvatar: "https://ui-avatars.com/api/?name=Nomsa+Khumalo&background=0d6efd&color=fff",
    sellerPhone: "27856667777",
    sellerUniversity: "Rhodes University",
    sellerRating: 4.6,
    sellerMemberSince: "January 2024",
    verified: true,
    paymentMethods: ["Cash"],
    imageUrl: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=600&h=400&fit=crop",
  },
  {
    id: "6",
    title: "Web Development & Design",
    description: "Need a website or help with coding projects? I specialize in React, Node.js, and responsive design. Student-friendly pricing.",
    price: 300,
    category: "tech",
    location: "University of Cape Town",
    sellerName: "David Chen",
    sellerAvatar: "https://ui-avatars.com/api/?name=David+Chen&background=6f42c1&color=fff",
    sellerPhone: "27863334444",
    sellerUniversity: "University of Cape Town",
    sellerRating: 4.9,
    sellerMemberSince: "November 2023",
    verified: true,
    paymentMethods: ["EFT", "Card"],
    imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&h=400&fit=crop",
  },
  {
    id: "7",
    title: "Graphic Design Services",
    description: "Professional graphic design for posters, logos, social media content, and more. Quick turnaround and unlimited revisions.",
    price: 180,
    category: "tech",
    location: "University of Johannesburg",
    sellerName: "Amara Okafor",
    sellerAvatar: "https://ui-avatars.com/api/?name=Amara+Okafor&background=6f42c1&color=fff",
    sellerPhone: "27871118888",
    sellerUniversity: "University of Johannesburg",
    sellerRating: 4.8,
    sellerMemberSince: "February 2024",
    verified: true,
    paymentMethods: ["Cash", "EFT"],
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&h=400&fit=crop",
  },
  {
    id: "8",
    title: "Fitness Training & Nutrition",
    description: "Personal training and nutrition coaching. Customized workout plans and meal prep guidance. Transform your body and health!",
    price: 220,
    category: "beauty",
    location: "University of KwaZulu-Natal",
    sellerName: "Mandla Zulu",
    sellerAvatar: "https://ui-avatars.com/api/?name=Mandla+Zulu&background=198754&color=fff",
    sellerPhone: "27885559999",
    sellerUniversity: "University of KwaZulu-Natal",
    sellerRating: 4.9,
    sellerMemberSince: "October 2023",
    verified: true,
    paymentMethods: ["Cash", "EFT", "Card"],
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop",
  }
];

// Universities List
const universities = [
  "University of Cape Town",
  "University of Witwatersrand",
  "University of Johannesburg",
  "Stellenbosch University",
  "University of Pretoria",
  "University of KwaZulu-Natal",
  "Rhodes University",
  "Nelson Mandela University",
  "North-West University",
  "University of the Free State",
];

// Categories
const categories = [
  { value: "tutoring", label: "Tutoring", icon: "bi-book" },
  { value: "tech", label: "Tech", icon: "bi-laptop" },
  { value: "beauty", label: "Beauty", icon: "bi-scissors" },
  { value: "food", label: "Food", icon: "bi-basket" },
  { value: "transport", label: "Transport", icon: "bi-car-front" },
];

// Demo Reviews
const demoReviews = [
  {
    id: "1",
    reviewerName: "Sarah Johnson",
    reviewerAvatar: "https://ui-avatars.com/api/?name=Sarah+Johnson&background=random",
    rating: 5,
    comment: "Amazing tutor! Helped me pass my Python exam with flying colors. Very patient and explains concepts clearly.",
    date: "2 weeks ago",
  },
  {
    id: "2",
    reviewerName: "Michael Brown",
    reviewerAvatar: "https://ui-avatars.com/api/?name=Michael+Brown&background=random",
    rating: 5,
    comment: "Highly recommend! Worth every cent. My understanding of data structures improved dramatically.",
    date: "1 month ago",
  },
  {
    id: "3",
    reviewerName: "Precious Ndlovu",
    reviewerAvatar: "https://ui-avatars.com/api/?name=Precious+Ndlovu&background=random",
    rating: 4,
    comment: "Great service! Very professional and knowledgeable. Would definitely use again.",
    date: "3 weeks ago",
  }
];
